// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZwajApp.API.Model;

namespace ZwajApp.API.Migrations
{
    [DbContext(typeof(dbcontext))]
    [Migration("20201105230906_Fullname")]
    partial class Fullname
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113");

            modelBuilder.Entity("ZwajApp.API.Model.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateAdded");

                    b.Property<string>("Description");

                    b.Property<bool>("IsMain");

                    b.Property<int>("UserID");

                    b.Property<string>("url");

                    b.HasKey("Id");

                    b.HasIndex("UserID");

                    b.ToTable("photo");
                });

            modelBuilder.Entity("ZwajApp.API.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("DateofBirth");

                    b.Property<string>("Intersstes");

                    b.Property<string>("Introduction");

                    b.Property<string>("Knowas");

                    b.Property<DateTime>("LastActive");

                    b.Property<string>("LookingFor");

                    b.Property<byte[]>("Passwordhash");

                    b.Property<string>("Username");

                    b.Property<string>("gender");

                    b.Property<byte[]>("passwordsalt");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ZwajApp.API.Model.value", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("name");

                    b.HasKey("ID");

                    b.ToTable("values");
                });

            modelBuilder.Entity("ZwajApp.API.Model.Photo", b =>
                {
                    b.HasOne("ZwajApp.API.Model.User", "User")
                        .WithMany("photos")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
